#!/bin/bash
# doit [build] [shell]

set -e
DOCKER_TAG=measurementlab/pyrunner

if [ x$1 = xbuild ]; then
  shift
  # Copy some stuff from the juptyer plotting/dev area
  mkdir -p tmp
  cp ../plottools/*.py tmp
  sudo docker build . -t $DOCKER_TAG
  echo "Consider: docker push $DOCKER_TAG"
fi

set -x
sudo docker run --net=host \
  -v  ~/.config/gcloud/legacy_credentials/mattmathis@google.com:/creds \
  -e GOOGLE_APPLICATION_CREDENTIALS=/creds/adc.json \
  --user $UID --group-add users \
  -it $DOCKER_TAG "$*"
