#!/bin/bash

# Build inspection scripts

function mkview {
  # mkview target, file, project
  target=$1		# dataset.view
  file=$2
  sourceset=${3-'NONE'}		# source file prefix
  direction=$4
  
  ProjectID=mlab-sandbox  # for target and execution


  # Forbid tabs
  if fgrep -s $'\t' $file ; then
    echo "Error: $file contains tabs"
    exit 2
  fi

  date=`date`
  view=`echo "-- Gemerated by $USER $date" ; \
    sed -e 's/"/'"'/g" \
    -e "s;{{ProjectID}};${sourceproject};" \
    -e "s;{{Direction}};${direction};" \
    -e "s;{{Datasource}};${sourceset};" \
    -e "s;{{query}};${file};" $file `

  bq rm \
    --force \
    --project_id $ProjectID \
    "${target}"

  echo "Create ${ProjectID}.${target} from $sourceset using $file"

  bq mk \
    --force \
    --view "$view" \
    --use_legacy_sql=false \
    --project_id=${ProjectID} \
    --description "test_view compiled: $(date)" \
    "${target}"
};

###### Main ######

# Traceroute
mkview inspector.traceroute_prod inspect_traceroute.sql measurement-lab.ndt.traceroute
mkview inspector.traceroute_prod_legacy inspect_traceroute_legacy.sql mlab-oti.base_tables.traceroute_legacy
while read name source ; do
    mkview inspector.traceroute_${name} inspect_traceroute_base_tables.sql $source.base_tables.traceroute
done <<EOF
oti mlab-oti
staging mlab-staging
sandbox mlab-sandbox
EOF

# Traceroute union
mkview inspector.union_traceroute_download union_traceroute.sql

# NDT Component views
legacysubsources="web100 ndt5"
componentsubsources="ndt7"
while read name source ; do
  for direction in uploads downloads ; do
    for subsource in $legacysubsources ; do
      mkview  inspector.ndt_${name}_${subsource}_${direction} inspect_ndt_legacy.sql \
        ${source}.library.ndt_unified_${subsource} ${direction}
    done
    for subsource in $componentsubsources ; do
      mkview  inspector.ndt_${name}_${subsource}_${direction} inspect_ndt_components.sql \
        ${source}.library.ndt_unified_${subsource} ${direction}
    done
  done
done <<EOF
prod mlab-oti
staging mlab-staging
sandbox mlab-sandbox
EOF

# NDT Unified views
mkview mm_unified_testing.ndt_ndt7_Downloads inspect_ndt_components.sql mlab-sandbox.library.ndt_unified_ndt7 downloads
mkview mm_unified_testing.ndt_sandbox_unified inspect_ndt_unified.sql mlab-sandbox.mm_unified_testing
mkview inspector.ndt_sandbox_unified inspect_ndt_unified.sql mlab-sandbox.ndt
mkview inspector.ndt_staging_unified inspect_ndt_unified.sql mlab-staging.ndt
mkview inspector.ndt_public_unified inspect_ndt_unified.sql measurement-lab.ndt



