from jupyter/datascience-notebook
# https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/Dockerfile
run pip install --upgrade google-cloud-bigquery google-cloud-storage zstandard
