#!/bin/bash
# doDockerPyplot [build] [shell]

set -eo pipefail
shopt -s nullglob
DOCKER_TAG=measurementlab/nbrunner

# deduce the user credentials: fail if not exactly one

CREDS=$(echo ~/.config/gcloud/legacy_credentials/*)
if [ "$(echo "$CREDS" | wc -w)" != 1 ]; then
  echo "Did not find exactly one credential: $CREDS"
  exit 2
fi

if [ "x$1" = xbuild ]; then
  shift
  sudo docker build . -t $DOCKER_TAG
  echo "Consider: docker push $DOCKER_TAG"
fi

doshell=""
if [ "x$1" = xshell ]; then
  shift
  doshell="-it --entrypoint=/bin/bash"
fi

DATADIR=$HOME/data
PWD="$(pwd)"

sudo docker run --net=host -v "$PWD":"$PWD" -v "$DATADIR":/data \
  -v  ~/.config/gcloud/legacy_credentials/mattmathis@google.com:/creds \
  -w "$PWD" -e GOOGLE_APPLICATION_CREDENTIALS=/creds/adc.json \
  --user $UID --group-add users \
  $doshell $DOCKER_TAG
