#!/bin/bash
# doit [build] [shell]

set -e

if [ x$1 = xbuild ]; then
  shift
  sudo docker build . -t nbrunner
fi

if [ x$1 = xshell ]; then
  shift
  doshell="-it --entrypoint=/bin/bash"
fi

DATADIR=$HOME/data

sudo docker run --net=host -v `pwd`:`pwd` -v $DATADIR:/data \
  -v  ~/.config/gcloud/legacy_credentials/mattmathis@google.com:/creds \
  -w `pwd` -e GOOGLE_APPLICATION_CREDENTIALS=/creds/adc.json \
  --user $UID --group-add users \
  $doshell nbrunner

exit

# Cmd  TEST_ONLY_BUILD=1
# "julia -e 'import Pkg; Pkg.update()' &&     (test $TEST_ONLY_BUILD || julia -e 'import Pkg; Pkg.add(\"HDF5\")') &&     julia -e \"using Pkg; pkg\\\"add IJulia\\\"; pkg\\\"precompile\\\"\" &&     mv $HOME/.local/share/jupyter/kernels/julia* $CONDA_DIR/share/jupyter/kernels/ &&     chmod -R go+rx $CONDA_DIR/share/jupyter &&     rm -rf $HOME/.local &&     fix-permissions $JULIA_PKGDIR $CONDA_DIR/share/jupyter"

