#!/bin/bash

# install all views locally

tool=bqsandbox  # Makes views in mlab-sandbox.mm_unified_testing

set -e

(cd ~/Projects/etl-schema/views

# New ndt_intermediate
$tool ../views/ndt_intermediate/extended_ndt7_downloads.sql
$tool ../views/ndt_intermediate/extended_ndt5_downloads.sql
$tool ../views/ndt_intermediate/extended_web100_downloads.sql
$tool ../views/ndt_intermediate/extended_ndt7_uploads.sql
$tool ../views/ndt_intermediate/extended_ndt5_uploads.sql
$tool ../views/ndt_intermediate/extended_web100_uploads.sql

# New unified 
$tool ../views/ndt/unified_downloads.sql
$tool ../views/ndt/unified_uploads.sql

# New ndt_raw
$tool ../views/ndt_raw/web100_legacy.sql
$tool ../views/ndt_raw/ndt5_legacy.sql
$tool ../views/ndt_raw/traceroute_legacy.sql
$tool ../views/ndt_raw/tcpinfo_legacy.sql
$tool ../views/ndt_raw/annotation.sql
$tool ../views/ndt_raw/ndt7.sql
)

exit



# bq query --project_id mlab-sandbox "$(cat test.sql)"



